### ISSUE TITLE
[Feature] Add python2 compatibility via "future imports"

### ISSUE THREAD

**Issue by sicklybeans** [sicklybeans/sjb_cheatsheet#21]
http://python-future.org/quickstart.html

**Comment by samuelbryant** [comment]
Python 2 compatibiity seems too hard. There are several issues. Even with pasteurization there are issues with the abc.ABCMeta vs abc.ABC variables. But perhaps the biggest issue is with the enum library. PriorityEnum.DEFAULT.value is valid in python3 but not python2.

For the moment, I'm marking this as won't fix
